### ISSUE TITLE
error release

### ISSUE THREAD

**Issue by arademaker** [FredsoNerd/py-ownpt#14]
```
INFO:root:formatting into LMF format
INFO:ownpt:start formating lexical resource
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ar/work/wn/venv/lib/python3.8/site-packages/pyownpt/cli/to_lmf.py", line 94, in <module>
    _parse(parser.parse_args())
  File "/Users/ar/work/wn/venv/lib/python3.8/site-packages/pyownpt/cli/to_lmf.py", line 41, in _parse
    lmf_format(ownpt_filapaths, ili_map_filapath, output_filepath, lexicon_id,
  File "/Users/ar/work/wn/venv/lib/python3.8/site-packages/pyownpt/cli/to_lmf.py", line 62, in lmf_format
    ownpt_lmf = OWN_LMF(ownpt, ili_map, lexicon_id, label, version, lang,
  File "/Users/ar/work/wn/venv/lib/python3.8/site-packages/pyownpt/ownlmf.py", line 33, in format
    lexical_resource.append(self.get_lexicon_lmf())
  File "/Users/ar/work/wn/venv/lib/python3.8/site-packages/pyownpt/ownlmf.py", line 42, in get_lexicon_lmf
    lexicon = Element("Lexicon", id=self.lexicon_id, label=self.label, status=self.status,
  File "src/lxml/etree.pyx", line 3022, in lxml.etree.Element
  File "src/lxml/apihelpers.pxi", line 131, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 119, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 317, in lxml.etree._initNodeAttributes
  File "src/lxml/apihelpers.pxi", line 334, in lxml.etree._addAttributeToNode
  File "src/lxml/apihelpers.pxi", line 1538, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'NoneType'
rm: log-repair: No such file or directory
```

**Comment by arademaker** [comment]
running `sh release.sh` where release.sh is 

```
% cat release.sh
python -m pyownpt.cli.update data/own-pt-* --wns dump/wn.jsonl --vts dump/votes.jsonl --sgs dump/suggestion-* -l pt -u arademaker vcvpaiva -o own-pt.nt -v
python -m pyownpt.cli.split own-pt.nt -l pt -e ttl -o data -v
python -m pyownpt.cli.statistics --ownpt data/own-pt-* --ownen data/own-en-* -v
python -m pyownpt.cli.to_lmf data/own-pt-* ili-map.ttl -li own-pt -lb OpenWordnet-PT -vr 1.0 -lg pt -cs 1.0 --status checked -o own-pt-lmf-10.xml -v
python -m pyownpt.cli.to_lmf data/own-en-* ili-map.ttl -li own-en -lb OpenWordnet-EN -vr 1.0 -lg en -cs 1.0 --status checked -o own-en-lmf-10.xml -v
rm own-pt.nt log-repair log-update
```

**Comment by fredsonaguiar** [comment]
Your'e using an old file.

Updated `release.sh` is available in https://github.com/own-pt/py-ownpt/blob/f13965303bfdba0aebd205397951bde0b2eb9aab/release.sh, which is up to date with the lib
